BlogApplication/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlogApplication.Models
{
    public class Blog
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Blog Id")]
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public virtual Category Categories { get; set; }

        [Display(Name = "Photo1")]
        public string Photo1 { get; set; }

        [Display(Name = "Description1")]
        public string Description1 { get; set; }

        [Display(Name = "Photo2")]
        public string Photo2 { get; set; }

        [Display(Name = "Description2")]
        public string Description2 { get; set; }

        [Display(Name = "Photo3")]
        public string Photo3 { get; set; }

        [Display(Name = "Description3")]
        public string Description3 { get; set; }

        [Display(Name = "Photo4")]
        public string Photo4 { get; set; }

        [Display(Name = "Description4")]
        public string Description4 { get; set; }

        [Display(Name = "Photo5")]
        public string Photo5 { get; set; }

        [Display(Name = "Description5")]
        public string Description5 { get; set; }

        

    }
}

BlogApplication/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogApplication.Models;
using static System.Net.WebRequestMethods;

namespace BlogApplication.Controllers
{
    
    public class BlogsController : Controller
    {
        private DbBlogContext db = new DbBlogContext();
        SaveImage Image = SaveImage.CreateObject();

        private string ImageSaver(HttpPostedFileBase Photo)
        {
            if (Photo != null && Photo.ContentLength > 0)
            {
                string filename = "./../Images/" + Image.Save(Photo);
                return filename;
            }

            return " ";
        }

        // GET: Blogs
        [Authorize]
        public ActionResult Index(int? Page)
        {
            var blogs = db.blogs.Include(b => b.Categories);

            return View(blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.categories, "CategoryId", "Name");
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,Title,CategoryId,Description1,Description2,Description3,Description4,Description5")] Blog blog, HttpPostedFileBase Photo1, HttpPostedFileBase Photo2, HttpPostedFileBase Photo3, HttpPostedFileBase Photo4, HttpPostedFileBase Photo5)
        {
            if (ModelState.IsValid)
            {

                blog.Photo1 = ImageSaver(Photo1);
                blog.Photo2 = ImageSaver(Photo2);
                blog.Photo3 = ImageSaver(Photo3);
                blog.Photo4 = ImageSaver(Photo4);
                blog.Photo5 = ImageSaver(Photo5);



                string[] descriptionProperties = { "Title", "Description1", "Description2", "Description3", "Description4", "Description5" };
                foreach (var prop in descriptionProperties)
                {
                    if (string.IsNullOrEmpty(blog.GetType().GetProperty(prop).GetValue(blog) as string))
                    {
                        blog.GetType().GetProperty(prop).SetValue(blog, " ");
                    }
                }


                db.blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.categories, "CategoryId", "Name", blog.CategoryId);
            return View(blog);
        }


        [HttpGet]
        [Authorize]
        public ActionResult ChangePhoto(int? id, int Photo)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var Blog = db.blogs.Find(id);
            TempData["ChangePhotoNumber"] = Photo;

            return View(Blog);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ChangePhoto(HttpPostedFileBase Photo, int id)
        {
            int ChangePhotoNumber = Convert.ToInt32(TempData["ChangePhotoNumber"].ToString());

            var Blog = db.blogs.Find(id);


            switch (ChangePhotoNumber)
            {
                case 1:
                    if (Blog.Photo1 != null)
                    {
                        Image.Delete(Blog.Photo1);
                    }
                    Blog.Photo1 = ImageSaver(Photo);
                    break;
                case 2:
                    if (Blog.Photo2 != null)
                    {
                        Image.Delete(Blog.Photo2);
                    }
                    Blog.Photo2 = ImageSaver(Photo);
                    break;
                case 3:
                    if (Blog.Photo3 != null)
                    {
                        Image.Delete(Blog.Photo3);
                    }
                    Blog.Photo3 = ImageSaver(Photo);
                    break;
                case 4:
                    if (Blog.Photo4 != null)
                    {
                        Image.Delete(Blog.Photo4);
                    }
                    Blog.Photo4 = ImageSaver(Photo);
                    break;
                case 5:
                    if (Blog.Photo5 != null)
                    {
                        Image.Delete(Blog.Photo5);
                    }
                    Blog.Photo5 = ImageSaver(Photo);
                    break;
            }

            db.Entry(Blog).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Edit", new { id });
        }


        // GET: Blogs/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.categories, "CategoryId", "Name", blog.CategoryId);
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,CategoryId,Description1,Description2,Description3,Description4,Description5")] Blog blog)
        {

            var Editblog = db.blogs.Find(blog.Id);
            Editblog.Title = blog.Title;
            Editblog.CategoryId = blog.CategoryId;
            Editblog.Description1 = blog.Description1;
            Editblog.Description2 = blog.Description2;
            Editblog.Description3 = blog.Description3;
            Editblog.Description4 = blog.Description4;
            Editblog.Description5 = blog.Description5;


            string[] descriptionProperties = { "Title", "Description1", "Description2", "Description3", "Description4", "Description5" };
            foreach (var prop in descriptionProperties)
            {
                if (string.IsNullOrEmpty(Editblog.GetType().GetProperty(prop).GetValue(Editblog) as string))
                {
                    Editblog.GetType().GetProperty(prop).SetValue(Editblog, " ");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(Editblog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.categories, "CategoryId", "Name", blog.CategoryId);
            return View(blog);
        }

        // GET: Blogs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Blog blog = db.blogs.Find(id);




        //    if (blog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(blog);
        //}

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.blogs.Find(id);

            Image.Delete(blog.Photo1);
            Image.Delete(blog.Photo2);
            Image.Delete(blog.Photo3);
            Image.Delete(blog.Photo4);
            Image.Delete(blog.Photo5);

            db.blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogApplication/Views/Blogs/ChangePhoto.cshtml
@model BlogApplication.Models.Blog
@{
    ViewBag.Title = "ChangePhoto";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="custom-border-bottom py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="/Products/Index">Admin</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Change Product photo</strong></div>
        </div>
    </div>
</div>

<div class="site-section mb-5" style="margin-top:30px">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="p-3 p-lg-5 border">
                    @using (Html.BeginForm("ChangePhoto", "Blogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        <div class="form-horizontal">
                            <h4 class="text-black">Product Images</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">

                                <div class="col-md-12">
                                    <input type="file" name="Photo" id="Photo" onchange="previewFile1();">
                                    <br />
                                    <br />
                                    <center>
                                        <img id="PhotoPreviewPhoto" alt="Preview" src="~/images/uploadphoto.jpg" name="PhotoPreviewPhoto" style="width:70%;max-width:70%" />
                                    </center>
                                </div>
                            </div>
                            <div class="form-group" style="display:none">
                                <input id="prodid" name="prodid" type="hidden" value="@Model.Id" />
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Upload" class="btn btn-black" style="padding-top:10px" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>
<script defer>
    function preview(id, imgid) {
        let inputid = document.querySelector(`#${id}`).addEventListener("change", function (e) {
            let file = e.target.files[0];
            let imageURL = URL.createObjectURL(file)
            let targetImage = document.getElementById(`${imgid}`)
            targetImage.src = imageURL
        })
    }

    preview("Photo", "PhotoPreviewPhoto")
</script>

BlogApplication/Views/Blogs/Create.cshtml
@model BlogApplication.Models.Blog

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




@using (Html.BeginForm("Create","Blogs",FormMethod.Post, new { enctype = "multipart/form-data" }))
{


<div class="form-horizontal p-3 p-md-5 my-3" style="border-radius: 16px; box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">

    <div class="d-flex justify-content-center mb-3">
        <h3>Add Blog</h3>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group my-4">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group my-4">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Photo1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo1, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <input type="file" name="Photo1" id=" Photo1" />

    <div class="form-group my-4">
        @Html.LabelFor(model => model.Description1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description1, new { rows = "5", cols = "10", @class = "form-control" })
            @*@Html.EditorFor(model => model.Description1, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Description1, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="file" name="Photo2" id="Photo2" />

    <div class="form-group my-4">
        @Html.LabelFor(model => model.Description2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description2, new { rows = "5", cols = "10", @class = "form-control" })
            @*@Html.EditorFor(model => model.Description2, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Description2, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="file" name="Photo3" id="Photo3" />

    <div class="form-group my-4">
        @Html.LabelFor(model => model.Description3, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description3, new { rows = "5", cols = "10", @class = "form-control" })
            @*@Html.EditorFor(model => model.Description3, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Description3, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="file" name="Photo4" id="Photo4" />

    <div class="form-group my-4">
        @Html.LabelFor(model => model.Description4, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description4, new { rows = "5", cols = "10", @class = "form-control" })
            @*@Html.EditorFor(model => model.Description4, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Description4, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="file" name="Photo5" id="Photo5" />

    <div class="form-group my-4">
        @Html.LabelFor(model => model.Description5, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.Description1, new { rows = "5", cols = "10", @class = "form-control" })
            @*@Html.EditorFor(model => model.Description4, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Description5, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group my-4">
        <div class="col-md-offset-2 col-md-12">
            <input type="submit" value="Create" onclick="disablebutton()" id="blogcreatebutton" class="btn btn-success" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function disablebutton() {
        var button = getElementById("blogcreatebutton");
        button.disabled = true;
    }
</script>

BlogApplication/Views/Blogs/Delete.cshtml
@model BlogApplication.Models.Blog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categories.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description5)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
      

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlogApplication/Views/Blogs/Details.cshtml
@model BlogApplication.Models.Blog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categories.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description5)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogApplication/Views/Blogs/Index.cshtml
@model IEnumerable<BlogApplication.Models.Blog>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<section>
    <div class="container-fluid d-flex justify-content-center flex-wrap">


        @foreach (var item in Model)
        {
            <div class="card card-Admin-custom-css m-3 ">
                <div class="row">
                    <div class="col-5">
                        <img src="@item.Photo1" class="card-img-top" alt="...">
                    </div>
                    <div class="col-7">
                        <div class="card-body blog-card-body p-0">
                            <p class="card-category">
                                @Html.DisplayFor(modelItem => item.Categories.Name)
                            </p>
                            <p class="card-text card-title">  @Html.DisplayFor(modelItem => item.Title) </p>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                            @*@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new {@class = "btn btn-danger" })*@
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</section>

<br />